<?php 
    if(!$this->connect ->isAdmin()): 
        header("location:index.php");
        exit();
    endif; 
?>
<!-- PAGE : add a player in a season -->
<section class="section">

    <h2 class="h2">Affilier un joueur à un effectif</h2>

    <!-- show info message on the page is message is isset -->
    <?php if(isset($_GET['message'])): ?>
        <p class="<?= htmlspecialchars($_GET['class']) ?>"><?= htmlspecialchars($_GET['message'])?><p>
    <?php endif; ?>

    <!-- admin tool menu -->
    <nav>
        <ul class="admin-tools">
            <li><a class="link" href="index.php?action=admin" title="menu admin"><i class="fas fa-arrow-circle-left"></i></a></li>
        </ul>
    </nav>
    
    <!-- notice for add a player in a season -->
    <div class="info-box">
        <div>
            <i class="fas fa-info-circle"></i>
        </div>
        <div>
            <p>Pour affilier un joueur à un effectif, selectionnez la saison concernée et le joueur à ajouter </p>
            <p>Pour creer un joueur, veuillez suivre ce lien : <a class="link" href="index.php?action=create_player" title="creer un joueur">creer un joueur</a><p>
        </div>
    </div>

    <!-- form for add a player in a season -->
    <form class="form" action="index.php?action=player_to_season" method="POST" enctype="multipart/form-data">
        
        <div>
            <label for="season">Saison : </label>
            <select name="season" id="season" >
                <?php foreach($seasonSelect as $item): ?>
                    <option value="<?=htmlspecialchars($item['id_saison']) ?>"><?=htmlspecialchars($item['annee']) ?></option>
                <?php endforeach; ?>
            </select>
        </div>

        <div>
            <label for="player">Joueur à affilier : </label>
            <select name="player" id="player" >
                <?php foreach($playerSelect as $player): ?>
                    <option value="<?=htmlspecialchars($player['id_joueurs']) ?>"><?=htmlspecialchars($player['nom']) ." ". htmlspecialchars($player['prenom']) ?></option>
                <?php endforeach; ?>
            </select>
        </div>
        
        <div class="submit-contenair">
            <input class="btn-link" type="submit" name="submit" value="Valider">
            <input class="btn-link" type="reset" name="Annuler" value="effacer le contenu">
        </div>
    </form>
</section>