<?php 
    if(!$this->connect ->isAdmin()): 
        header("location:index.php");
        exit();
    endif; 
?>

<!-- PAGE : CREATE GAME -->
<section class="section">

    <h2 class="h2">Créer une rencontre</h2>
    
    <!-- admin tool menu -->
    <nav>
    <ul class="admin-tools">
            <li><a class="link" href="index.php?action=admin" title="menu admin"><i class="fas fa-arrow-circle-left"></i></a></li>
        </ul>
    </nav>

    <!-- show info message on the page is message is isset -->
    <?php if(isset($_GET['message'])): ?>
        <p class="<?= htmlspecialchars($_GET['class']) ?>"><?= htmlspecialchars($_GET['message']) ?><p>
    <?php endif; ?>
    
    <!-- Form for add game -->
    <form class="form" name="form" action="index.php?action=create_game" method="POST" >

        <div>
            <label for="competition">Compétition: </label>
            <select name="competition" id="competition">
                    <option value="Ligue Magnus">Ligue Magnus</option>
                    <option value="coupe de france">Coupe de France</option>
                    <option value="amical">Amical</option>
                    <option value="chl">CHL</option>
                    <option value="continental">Continental Cup</option>
            </select>
        </div>

        <div>
            <label for="date_match">Date de la rencontre:</label>
            <input type="date" name="date_match" id="date_match" required>
        </div>

        <div>
            <label for="domicile">Equipe Domicile: </label>
            <select name="domicile" id="domicile">
                <?php foreach($teams as $team): ?>
                    <option value="<?=htmlspecialchars($team['id_equipe']) ?>"><?= htmlspecialchars($team['ville']) ?></option>
                <?php endforeach;?>
            </select>
        </div>

        <div>
            <label for="score_dom">Score domicile:  </label>
            <input type="number" min="0" max="20" name="score_dom" id="score_dom">
        </div>

        <div>
            <label for="exterieur">Equipe Exterieur: </label>
            <select name="exterieur" id="exterieur">
                <?php foreach($teams as $team): ?>
                    <option value="<?=htmlspecialchars($team['id_equipe']) ?>"><?= htmlspecialchars($team['ville']) ?></option>
                <?php endforeach;?>
            </select>
        </div>

        <div>
            <label for="score_ext">Score Exterieur:</label>
            <input type="number" min="0" max="20" name="score_ext" id="score_ext">
        </div>

        <div>
            <label for="statut">Report ou annulation : </label>
            <select name="statut" id="statut">
                    <option value="">conforme</option>
                    <option value="reporté">report</option>
                    <option value="annulé">annulation</option>
            </select>
        </div>
        

        <div class="submit-contenair">
            <input class="btn-link" type="submit" name="submit" value="Valider">
            <input class="btn-link" type="reset" name="Annuler" value="effacer le contenu">
        </div>

    </form>
</section>