<?php 
    if(!$this->connect ->isAdmin()): 
        header("location:index.php");
        exit();
    endif; 
?>

<!-- PAGE for Create a player-->
<section class="section">

    <h2 class="h2">Creer un joueur</h2>
    
    <!-- admin tool menu -->
    <nav>
        <ul class="admin-tools">
            <li><a class="link" href="index.php?action=admin" title="menu admin"><i class="fas fa-arrow-circle-left"></i></a></li>
        </ul>
    </nav>

    <!-- show info message on the page is message is isset -->
    <?php if(isset($_GET['message'])): ?>
        <p class="<?= htmlspecialchars($_GET['class']) ?>"><?= htmlspecialchars($_GET['message']) ?><p>
    <?php endif; ?>
    
    <!-- Form for create a player -->
    <form class="form" name="form" action="index.php?action=create_player" method="POST" enctype="multipart/form-data">

        <div>
            <label for="firstname">Prénom du joueur:</label>
            <input type="text" name="firstname" id="firstname" required> 
        </div>

        <div>
            <label for="name">Nom du joueur:</label>
            <input type="text" name="name" id="name" required> 
        </div>

        <div>
            <label for="number">Numéro du joueur: </label>
            <input type="number" min="1" max="99" name="number" id="number" required>
        </div>

        <div>
            <label for="birthdate">Date de Naissance:</label>
            <input type="date" name="birthdate" id="birthdate" required>
        </div>

        <div>
            <label for="nation">Nationnalité:</label>
            <input type="text" name="nation" id="nation" placeholder="Française" required> 
        </div>

        <div>
            <label for="height">Taille (cm):  </label>
            <input type="number" min="150" max="220" name="height" id="height" required>
        </div>

        <div>
            <label for="weight">Poids (kg):</label>
            <input type="number" min="60" max="120" name="weight" id="weight" required>
        </div>
        
        <div>
            <label for="position">Poste: </label>
            <select name="position" id="position">
                    <option value="Défenseur">Défenseur</option>
                    <option value="Attaquant">Attaquant</option>
                    <option value="Gardien">Gardien</option>
            </select>
        </div>

        <div>
            <label for="image">choisir la photo du joueur (si pas de choix, une image par defaut sera appliquée) : </label>
            <input type="hidden" name="MAX_FILE_SIZE" value="300000">
            <input type="file" name="image" id="image">
        </div>

        <div class="submit-contenair">
            <input class="btn-link" type="submit" name="submit" value="Valider">
            <input class="btn-link" type="reset" name="Annuler" value="effacer le contenu">
        </div>

    </form>
</section>