<?php 
    if(!$this->connect ->isAdmin()): 
        header("location:index.php");
        exit();
    endif; 
?>
<!-- PAGE player management -->
<section class="section">
    <h1 class="h1">Gestion des joueurs</h1>
    
    <!-- admin tool menu -->
    <nav>
        <ul class="admin-tools">
            <li><a class="link" href="index.php?action=admin" title="menu admin"><i class="fas fa-arrow-circle-left"></i></a></li>
            <li><a class="link" href="index.php?action=create_player" title="ajouter un joueur"><i class="fas fa-user-plus"></i></a></li>
        </ul>
    </nav>

    <!-- Show info message if message is isset -->
    <?php if(isset($_GET['message'])): ?>
    <p class="<?= htmlspecialchars($_GET['class']) ?>"><?= htmlspecialchars($_GET['message']) ?><p>
    <?php endif; ?>

    <!-- table for show and manage players -->
    <table class="table">
        <thead>
            <tr>
                <th>Joueur</th>
                <th>Numéro</th>
                <th>Poste</th>
                <th>Nationalité</th>
                <th>Taille</th>
                <th>Poids</th>
                <th>modifier</th>
                <?php if($adminSession->isAdmin() && $_SESSION['niveauAdmin']<20):?>
                <th>supprimer</th>
                <?php endif;?>
            </tr>
        </thead>

        <tbody>
            <?php foreach($playersManage as $item): ?>
            <tr>
                <td data-label="Joueur" ><?= htmlspecialchars($item['nom'])." " .htmlspecialchars($item['prenom']); ?></td>
                <td data-label="Numéro"><?= htmlspecialchars($item['numero']); ?></td>
                <td data-label="Poste"><?= htmlspecialchars($item['poste']); ?></td>
                <td data-label="Nationalité"><?= htmlspecialchars($item['nationalite']); ?></td>
                <td data-label="Taille"><?= htmlspecialchars($item['taille'])." cm"; ?></td>
                <td data-label="Poids"><?= htmlspecialchars($item['poids'])." kg"; ?></td>
                <td>
                    <a class="btn-modif" href="index.php?action=update_player&id_player=<?=htmlspecialchars($item['id_joueurs'])?>" title="modifier le joueur"><i class="fas fa-pencil-alt"></i></a>
                </td>
                <?php if($adminSession->isAdmin() && $_SESSION['niveauAdmin']<20):?>
                <td>
                    <form method="POST" action="index.php?action=delete_player">
                        <input type="hidden" name="photo_player" value="<?=htmlspecialchars($item['photo']) ?>" >    
                        <input type="hidden" name="delete_player" value="<?=htmlspecialchars($item['id_joueurs'])?>">
                        <button class="btn-delete" type="submit" value='supprimer' ><i class="fas fa-trash-alt"></i></button>
                    </form>                  
                </td>
                <?php endif;?>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</section>