<?php 
    if(!$this->connect ->isAdmin()): 
        header("location:index.php");
        exit();
    endif; 
?>

<!-- PAGE update article -->
<section class="section">

    <h2 class="h2">Modifier un Article</h2>

    <!-- Show info message if message is isset -->
    <?php if(isset($_GET['message'])): ?>
        <p class="<?= htmlspecialchars($_GET['class']) ?>"><?= htmlspecialchars($_GET['message']) ?><p>
    <?php endif; ?>

    <!-- form for upadte an article -->
    <form class="form form-article" name="form" action="index.php?action=update_article" method="POST" enctype="multipart/form-data">
        <input type="hidden" name="id_article" value="<?= htmlspecialchars($oneArticle['id_article']) ?>">
        <input type="hidden" name="id_cat" value="<?= htmlspecialchars($oneArticle['id_cat']) ?>">

        <div>
            <label for="article_titre">Titre</label>
            <input type="text" name="article_titre" id="article_titre" value="<?= htmlspecialchars($oneArticle['titre']) ?> " required> 
        </div>

        <div>
            <label for="article_image">choisir une image : </label>
            <input type="hidden" name="MAX_FILE_SIZE" value="300000"  />
            <input type="file" name="article_image" id="article_image" />
        </div>

        <div>
            <label for="article_contenu">Article : </label>
            <textarea name="article_contenu" cols="33" rows="10" id="article_contenu" required><?= htmlspecialchars($oneArticle['contenu']) ?></textarea>
        </div>

        <div>
            <label for="article_auteur">Auteur : </label>
            <input readonly name="article_auteur" id="article_auteur" value="<?= htmlspecialchars($oneArticle['prenom']).' '. htmlspecialchars($oneArticle['nom']) ?>">
        </div>
        
        <div>
            <label for="article-categorie">Catégorie : </label>
            <select name="article_category" id="article-categorie">
                <option value="<?=htmlspecialchars($oneArticle['id_article']) ?>"><?=htmlspecialchars($oneArticle['nom_cat']) ?></option>
                <?php foreach($categoriesList as $category): ?>
                    <option value="<?=htmlspecialchars($category['id_categorie']) ?>"><?=htmlspecialchars($category['nom_cat']) ?></option>
                <?php endforeach; ?>
            </select>
        </div>

        <div class="submit-contenair">
            <input class="btn-link" type="submit" name="submit" value="Valider"/>
            <input class="btn-link" type="reset" name="Annuler" value="effacer les modifications"/>
        </div>

    </form>
</section>