<?php 
    if(!$this->connect ->isAdmin()): 
        header("location:index.php");
        exit();
    endif; 
?>

<!-- PAGE for update a player -->
<section class="section">

    <h2 class="h2">Modifier un joueur</h2>

    <!-- Show info message if message is isset -->
    <?php if(isset($_GET['message'])): ?>
        <p class="<?= htmlspecialchars($_GET['class']) ?>"><?= htmlspecialchars($_GET['message']) ?><p>
    <?php endif; ?>

    <!-- Form for update a player -->
    <form class="form" name="form"  action="index.php?action=update_player" method="POST" enctype="multipart/form-data">

        <input type="hidden" name="id_player" value ="<?=htmlspecialchars($playerToUpdate['id_joueurs'])?>">

        <div>
            <label for="firstname">Prénom du joueur:</label>
            <input type="text" name="firstname" id="firstname" value="<?=htmlspecialchars($playerToUpdate['prenom'])?>" required> 
        </div>

        <div>
            <label for="name">Nom du joueur:</label>
            <input type="text" name="name" id="name" value="<?=htmlspecialchars($playerToUpdate['nom'])?>" required> 
        </div>

        <div>
            <label for="number">Numéro du joueur: </label>
            <input type="number" min="1" max="99" name="number" id="number" value="<?=htmlspecialchars($playerToUpdate['numero'])?>" required>
        </div>

        <div>
            <label for="birthdate">Date de Naissance:</label>
            <input type="date" name="birthdate" id="birthdate" value="<?=htmlspecialchars($playerToUpdate['date_de_naissance'])?>" required>
        </div>

        <div>
            <label for="nation">Nationnalité:</label>
            <input type="text" name="nation" id="nation" placeholder="Française"  value="<?=htmlspecialchars($playerToUpdate['nationalite'])?>" required> 
        </div>

        <div>
            <label for="height">Taille (cm):  </label>
            <input type="number" min="150" max="220" name="height" id="height" value="<?=htmlspecialchars($playerToUpdate['taille'])?>" required>
        </div>

        <div>
            <label for="weight">Poids (kg):</label>
            <input type="number" min="60" max="120" name="weight" id="weight" value="<?=htmlspecialchars($playerToUpdate['poids'])?>" required>
        </div>
        
        <div>
            <label for="position">Poste: </label>
            <select name="position" id="position">
                    <option value="<?=htmlspecialchars($playerToUpdate['poste'])?>" ><?=htmlspecialchars($playerToUpdate['poste'])?></option>
                    <option value="Défenseur">Défenseur</option>
                    <option value="Attaquant">Attaquant</option>
                    <option value="Gardien">Gardien</option>
            </select>
        </div>

        <div>
            <label for="image">Photo du joueur (si pas de choix, une image par defaut sera appliquée) : </label>
            <input type="hidden" name="MAX_FILE_SIZE" value="300000">
            <input type="file" name="image" id="image">
        </div>

        <div class="submit-contenair">
            <input class="btn-link" type="submit" name="submit" value="Valider">
            <input class="btn-link" type="reset" name="Annuler" value="effacer le contenu">
        </div>

    </form>
</section>