<section class="section">
	<h1 class="h1">L'équipe que nous supportons</h1>
	<article class="article-details">
		<figure>
			<img src="www/css/assets/img/tribunei.jpg" alt="photo déplacement">
		</figure>
		<p>
			Nous chantons, nous applaudissons, nous créons des tifos, dans le but de les encourager et les pousser vers la victoire, cette équipeque nous aimons tant depuis tant d'années peut se résumer en trois lettres BDL.
		</p>
		<p>
			Les Brûleurs de Loups, c'est ainsi que se nomme l'équipe que nous suivons depuis 1985, année de création de notre club de supporters.Ce nom ont le doit à Albert Fontaine, journaliste de Dauphiné Libéré dans les années 60, qui avait surnommé le club Grenoblois ainsi ,ce sera enen 1992 que ce nom sera  officiellement celui de l'équipe.
		</p>
		<h2 class="h2">Tout commence avec la légende du loup</h2>
		<p>
			Le surnom que porte notre équipe de hockeyeurs aujourd'hui, fait référence aux battues qui été organisées au 18ième siècle afin de fairedisparaître le loup de la région. Pour y parvenir le feu été alors allumé dans les bois.
        </P>
		<p>
			Aujourd'hui cette période est révolue, et le loup est désormais la mascotte des Isérois qui comptent bien mettre le feu à pôlesud chaque soir de match,les BDL sur la glace , les irrés en tribune !
		</p>
	</article>
</section>

<aside class= "section-palmares"  >
	<h2 class="h2bis">Palmarès </h2>
	<div class="palmares-content">
		<div>
			<p class="nb-cup"> 7 </p>
			<p class="name-cup"> Coupe Magnus </p>
		</div>
		<div>
			<p class="nb-cup"> 4 </p>
			<p class="name-cup"> Coupe De France </p>
		</div>
		<div>
			<p class="nb-cup"> 4 </p>
			<p class="name-cup"> Coupe De La Ligue </p>
		</div>
		<div>
            <p class="nb-cup"> 4 </p>
			<p class="name-cup"> Trophée des Champions </p>
		</div>
	</div>
</aside>
