<section class="section">
    <h1 class="h1">La tribune i</h1>

    <article class="article-details">
        <figure>
            <img src="www/css/assets/img/tribunei.jpg" alt="photo déplacement">
        </figure>

        <p>I comme irréductibles ...
        </p>

        <p>C’est notre lieu de rassemblement ! Là où nous chantons, agitons nos drapeaux. On se refait les actions de matchs, 
            on rigole, on s’amuse et bien entendu on pousse notre équipe à remporter la victoire !
        </p>
            
        <p>Pour ambiancer les matchs, nous essayons de proposer des animations en tribune, si les chants, tambours et drapeaux font partie intégrante de la 
            fête nous essayons grâce à notre atelier créatif de proposer des animations visuelles telles que la création de tifos.
        </p>

        <h2 class="h2">Hissez haut les tifos !</h2>
        <p>Draps, peintures, coutures, imagination et ambiance bon enfant sont au programme pour confectionner nos différents tifos.
            Si vous venez régulièrement aux matchs, alors nul doute que vous avez vu nos différentes créations ! 
            Nous avons créé des tifos sur les thèmes d’Asterix, de la région de Grenoble, pour nos 35 ans, mais aussi des 
            tifos pour les événements ponctuels comme Octobre Rose et Movember.
        </p>

        <h2 class="h2">A savoir sur notre tribune !</h2>
        <p>Notre tribune est ouverte à tout le monde, si vous avez envie de venir passer le match en notre compagnie vous êtes les 
            bienvenus. Toutefois nous tenons à préciser que notre tribune et une <strong>TRIBUNE SUPPORTERS !</strong>
            Par conséquent en venant dans notre tribune vous accepter :
        </p>
        <ul class="style-list-icone">
            <li>Que la plupart des supporters passent le match Debout !</li>
            <li>Qu’il y ait présence de tambours faisant de notre tribune un endroit plus bruyant que le reste de la patinoire.</li>
            <li>Les drapeaux sont régulièrement agités pouvant gêner la visibilité du jeu à certains moments du match.</li>
            <li>Malgré les places numérotées, nous considérons la tribune I comme PLACEMENT LIBRE afin de pouvoir y installer notre matériel.</li>
        </ul>
        

        <p>Envie de faire partie de la famille irréductibles ? Nous vous proposons de lire l’article sur les adhésions 
            en cliquant sur ce <a href="index.php?action=static_page&page=nousrejoindre" title="adhesion">lien vers les adhésions.</a>
        </p>

        <div class="iframe-box">
            <iframe width="560" height="315" src="https://www.youtube.com/embed/vvyKsBc6CI4" title="YouTube video Tifo des irréductibles" 
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" 
                allowfullscreen>
            </iframe>
        </div>

    </article>
</section>


