<section class="section">
    <h1 class="h1">Les déplacements</h1>

    <article class="article-details">
        <figure>
            <img src="www/css/assets/img/deplacement.jpg" alt="photo déplacement">
        </figure>
        
        <p>Tout au long de la saison, les Irréductibles organisent des déplacements pour soutenir les Brûleurs de Loups en dehors de Polesud.</p>
        <p>Même si depuis la nouvelle réforme du Championnat en double aller/retour et dernièrement la crise sanitaire, les déplacements sont moins fréquents,
        nous continuons à essayer de mettre en place un dispositif pour les rencontres régionales.
        </p>

        <h2 class="h2">Qui peut s'inscrire ?</h2>

        <p>Tout le Monde !</p>
        <p>Les inscriptions sont ouvertes à toute personne irréductibles ou non, il n'y a pas besoin d'être adhérent à notre club pour en profiter, 
            toutefois les membres de l'association sont prioritaires en cas de places insuffisantes.
            Pour les adhérents à jour de leur cotisation, le club des irréductibles prend en charge une partie du montant, ce qui permet de leur proposer
            un tarif attractif. <strong>Les mineurs ne peuvent s'inscrire seuls, un accompagnant majeur est obligatoire</strong>.
        </p>

        <h2 class="h2">Comment s'inscrire ?</h2>
        <p>Les inscriptions peuvent se faire : en vous rendant les soirs de match à la table des supporters, derrière la tibune i, 
            en nous envoyant un mail, ou en remplissant le formulaire de contact, ou par téléphone auprès de notre trésorier.</p>
        <p>Le réglement se réalise soit au momment de l'inscription, soit dans le bus le jour du départ.</p>
        <p>Pour les personnes extèrieures au club des Irréductibles, un accompte peut être demandé au moment de l'inscription</p>
        <p>Notre association ne dispose pas de moyens de paiement par carte bancaire, le réglement se fait alors soit par espèces ou par chèque.</p>
        <p><em>A noter !</em> Les déplacements en bus se font pas l'intermédiaire de notre partenaire PERRAUD. Un déplacement est validé lorsqu'un 
        certain quota de participants est atteint. </p>
        
        <h2 class="h2">Pourquoi faire un déplacement ?</h2>
        <p>Soutenir notre équipe à l'extérieur nous permet de montrer aux joueurs que nous sommes là pour jouer notre rôle de 7ième Homme,
        c'est aussi une occasion pour passer un moment entre supporters, amis et vivre un match autrement qu'à domicile, et parfois même jouer aux touristes pour les
        longs déplacements !
        </p>
        
    </article>
</section>

