<section class="section">
    <h1 class="h1">Mentions légales</h1>

    <article class="mentions">
        <div >
            <h2>L' ASSOCIATION</h2>
            <p>Régie par la loi du 1er Juillet 1901 et du Décret du 16 Aout 1901</p>
            <p>LES IRREDUCTIBLES, Club de supporters des Brûleurs de Loups de Grenoble</p>
            <p>Siège social fixé à l'Adresse du président de l'association</p>
            <p>Pésident en fonction: Alexis MASELLA</p>
        </div>

        <div >
            <h2>DEVELOPPEMENT & CREDITS</h2>
            <p>Ce site a été développé par David ROTOLO</p>
            <p>Les photos officielles et effectifs sont diffusés avec l'autorisation du club des Brûleurs de Loups</p>
            <p>Crédits photos officielles : bruleursdeloups.com / Fabien Baldino</p>
        </div>

        <div >
            <h2>HEBERGEUR</h2>
            <p>Non concerné pour le moment</p>
        </div>
        
        <div>
            <h2>CONDITIONS D'UTILISATION </h2>
            <p>Ce site est composé de différents langages web à savoir : HTML, CSS, Javascript, PHP, pour un meilleur confort d’utilisation il est recommandé de recourir à des navigateurs modernes comme  Safari, Firefox, Google Chrome, etc…
            </p>

            <p>Nous mettons tout en oeuvre pour assurer une information fiable, toutefois des erreurs ou omissions peuvent survenir. 
            L’internaute devra donc s’assurer de l’exactitude des informations.
            </p>

            <p>Des liens hypertextes peuvent pointer vers d'autres sites externes, nous ne disposons d'aucun moyen de contrôle concernant l'état de ces sites.

            Le club des Iréductibles ne peut être tenu pour responsable de tout dommage, de quelque nature que ce soit, résultant du contenu de ces sites ou sources externes,
            et notamment des informations, produits ou services qu’ils proposent, ou de tout usage qui peut être fait de ces éléments. 
            Les risques liés à cette utilisation incombent pleinement à l’internaute, qui doit se conformer à leurs conditions d’utilisation.  
            </p>
        </div>

        <div>
            <h2>DONNEES PERSONNELLES </h2>
            <p>Ce site n'utilise pas de Cookie</p>

            <p>Les seules informations enregistrées le sont lors de la soumission du formulaire de contact. Les informations envoyées via ce formulaire
                sont stockées dans notre base de données le temps que la demande soit traitée, et après avoir répondu à la sollicitation 
                les données sont supprimées de la base de données. Une alternative est proposée par un lien permettant de nous envoyer directement un mail sans passer par ce formulaire.
            </p>
        </div>

    </article>
</section>


