<section class="section">
    <h1 class="h1">Nous rejoindre, Adhésion</h1>

    <article class="article-details">
        <figure>
            <img src="www/css/assets/img/maillotirre.jpg" alt="photo déplacement">
        </figure>
        
        <h2 class="h2">Qui peut adhérer ?</h2>
        <p>Tout le monde, à condition de respecter les règles de l’association ainsi que sa charte.
            Les moins de 18 ans ne peuvent s’inscrire seuls. 
        <p>

        <h2 class="h2">Comment adhérer ?</h2>
        <p>Pour adhérer, récuperer le bulletin à la table des supporters où par simple demande et adressez-le nous avec votre règlement à l’adresse du  
            siège (Alexis MASELLA, 6 rue Voltaire 38360 Sassenage), 
            ou en nous rencontrant à la table des supporters située derrière notre tribune I.
        <p>

        <h2 class="h2">Les avantages</h2>
        <p>Les adhérents des irréductibles sont prioritaires et ont un tarif préférentiel pour les déplacements organisés par les Irréductibles.  
        La carte irréductibles permet également de bénéficier de remises chez certains de nos partenaires. 
        </p>

        <div class="static-elements-wrapper">
            <div>
                <h2 class="h2">Nos Tarifs</h2>
                <ul class="style-list-icone">
                    <li><strong>15 €</strong> pour le premier membre de la famille</li>
                    <li><strong>10 €</strong> pour le deuxième membre de la famille</li>
                    <li><strong>5 €</strong> pour le troisième membre de la famille</li>
                    <li><strong>Gratuit</strong> pour les 2 membres suivants</li>
                    <li><strong>5</strong> membres maximum par famille</li>
                    <li><strong>7 €</strong> pour les 10-18 ans</li>
                    <li><strong>Gratuit</strong> pour les moins de 10 ans</li>
                </ul>
            </div>

            <div>
            <h2 class="h2">Notre charte</h2>
                <ul class="style-list-icone">
                    <li>Encourager et soutenir les équipes en n'exigeant pas un spectacle à sa convenance </li>
                    <li>Etre courtois envers l'adversaire en appréciant chaque jeu effectué </li>
                    <li>Se rappeler que le hockey appartient aux joueurs et non au public </li>
                    <li>Permettre aux officiels de travailler en toute quiétude et respecter leurs décisions </li>
                    <li>Désapprouver tout manquement à l'esprit sportif </li>
                    <li>Condamner la violence sous toutes ses formes </li>
                    <li>Ne lancer aucun objet sur les joueurs, les officiels ou sur la glace </li>
                    <li>Ne jamais insulter ou harceler les joueurs ou les officiels </li>
                    <li>Chercher à augmenter sa connaissance du Hockey pour mieux l'apprécier </li>
                    <li>Rester toujours maître de soi malgré les influences de l'entourage </li>
                    <li>Toujours ensemble pour supporter notre équipe des Brûleurs de Loups </li>
                </ul>
            </div>
        </div>

    </article>
</section>


