<section class="section">
    <h1 class="h1">Qui sommes nous ?</h1>

    <article class="article-details">
        <figure>
            <img src="www/css/assets/img/tribune.jpg" alt="photo de la tribune supporter">
        </figure>
        
        <p>Depuis 1985 les Brûleurs de Loups de Grenoble peuvent compter sur le soutien d’un groupe de supporters présent 
            à chaque match et dont le but est de jouer le rôle du <em>septième Homme</em>, ce club de supporters s’appelle 
            <em>Les Irréductibles !</em>
        </p>

        <p>Depuis plus de 35 ans  ce groupe porte haut et fort les couleurs des BDL. Ils ont d’abord sévi à Clémenceau dans cette patinoire
            à la raisonnance parfaite, puis en 2001,<em> Polesud</em>, la nouvelle patinoire du sud de l’agglomération ouvre ses portes et bien entendu 
            les irréductibles sont de la partie ! D’abord en tribune H puis en tribune I, la famille irré s’y retrouve tous les soirs de matchs, 
            et font de leur mieux avec tambours, mégaphones et drapeaux pour supporter les Brûleurs de Loups.
        </p>

        <p>Notre groupe de supporters à vécu tout au long de ces années au rythme du hockey Grenoblois en partageant ainsi les meilleurs
            moments mais aussi les moins bons.
        </p>

        <h2 class="h2">A domicile comme à l'extérieur </h2>
        <p>
        les Irréductibles se sont aussi des milliers de kilomètres parcourus à travers la France pour suivre l’équipe lors de ses 
        déplacements. De vrais « fous » comme diront certains joueurs très contents de nous voir à l’autre bout de l’hexagone. 
        Rien ne nous arrête, ni le temps passé sur la route, ni la météo lorsqu’il a fallu braver les tempêtes de neige, 
        ni l’argent que cela nous a coûté, la preuve en est que certains ont investi dans un minibus pour les déplacements !
        </p>
        
        <aside class="static-aside">
            <h2 class="h2">Découvrez d'autres articles concernant les irréductibles</h2>
            <ul>
                <li><a class="link" href="index.php?action=static_page&page=latribunei" title="La tribune i">La tribune i</a></li>
                <li><a class="link" href="index.php?action=static_page&page=lesdeplacements" title="Les déplacements">Les déplacements</a></li>
                <li><a class="link" href="index.php?action=static_page&page=nousrejoindre" title="Nous rejoindre">Nous rejoindre</a></li>
            </ul>
        </aside>
    </article>
</section>


